# Generated by Django 3.1.3 on 2020-11-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201106_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Short_Description',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
