# Generated by Django 3.1.3 on 2020-11-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201107_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='Swapnil', max_length=20),
            preserve_default=False,
        ),
    ]
